{% set name = "tango-database" %}
{% set version = "5.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/TangoDatabase/-/archive/Database-Release-{{ version }}/TangoDatabase-Database-Release-{{ version }}.tar.gz
  sha256: bb0228358e0e1cc899fb5d1c3e50ca0462444bcc176e97e7410e34874c6f3fa7
  patches:
    - find-zeromq-win.patch  # [win]

build:
  number: 0

requirements:
  build:
    - cmake
    - make                    # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - libtool                 # [unix]
    - pkg-config              # [unix]
  host:
    - cppzmq
    - cpptango
    - mysql-devel
    - omniorb-libs

test:
  commands:
    # Databaseds --help returns 255, so grep the stderr for test
    - Databaseds --help 2>&1 | grep usage                  # [unix]
    - test -f $PREFIX/share/tango/db/create_db.sql         # [unix]
    - test -f $PREFIX/share/tango/db/create_db_tables.sql  # [unix]
    - test -f $PREFIX/share/tango/db/stored_proc.sql       # [unix]
    - Databaseds.exe --help 2>&1 | findstr usage           # [win]

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango Database Server
  description: |
    This is the Tango Database server.
    Tango-Controls is a software toolkit for building control systems.
  dev_url: https://gitlab.com/tango-controls/TangoDatabase

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
