{% set name = "tango-database" %}
{% set version = "5.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/TangoDatabase/-/archive/Database-Release-{{ version }}/TangoDatabase-Database-Release-{{ version }}.tar.gz
  sha256: beb0c79f9db361e5c49ae30f2601e27eb79b89500c088e29dc2328de88bd2c3d
  patches:
    - remove-db-client-compile-check.patch  # [build_platform != target_platform]

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
  host:
    - cppzmq
    - cpptango
    - mysql-devel
    - omniorb
    - omniorb-libs

test:
  commands:
    # Databaseds --help returns 255, so grep the stderr for test
    - Databaseds --help 2>&1 | grep usage
    - test -f $PREFIX/share/tango/db/create_db.sql
    - test -f $PREFIX/share/tango/db/create_db_tables.sql
    - test -f $PREFIX/share/tango/db/stored_proc.sql

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango Database Server
  description: |
    This is the Tango Database server.
    Tango-Controls is a software toolkit for building control systems.
  dev_url: https://gitlab.com/tango-controls/TangoDatabase

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
